name: cosmic-pull-request-build

on:
  pull_request:

jobs:
  maven-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup beta-nexus
        run: |
          mkdir -p ~/.m2
          echo "<settings><profiles><profile><id>beta-nexus</id><repositories><repository><id>beta-nexus</id><name>beta-nexus</name><url>https://beta-nexus.mcc.schubergphilis.com/content/groups/public</url></repository></repositories></profile></profiles><activeProfiles><activeProfile>beta-nexus</activeProfile></activeProfiles></settings>" | tee ~/.m2/settings.xml
      - name: Build with Maven
        run: mvn -B -f pom.xml clean install -U -Psystemvm -Psonar-ci-cosmic -Dcosmic.dir="${GITHUB_WORKSPACE}" -Dlog.file.management.server="/var/log/cosmic/management/management.log" -Dlog.rotation.management.server="/var/log/cosmic/management/management-%d{yyyy-MM-dd}.log.gz" -Dcosmic.tests.mockdb=true
